### ISSUE TITLE
Check App Vulnerabilities script unable to handle certain application DisplayNames

### ISSUE THREAD

**Issue by wise-io** [lwhitelock/NinjaOneAutomation#1]
**Script:** https://github.com/lwhitelock/NinjaOneAutomation/blob/main/DocumentationScripts/Check-App-Vulnerabilities.ps1

Unfortunately, `if ($null -notlike $DisplayName) {...}` fails with some application DisplayNames.

```
PS C:\Users\me> $DisplayName = "Test Application [Fail-Me]"
PS C:\Users\me> if ($null -notlike $DisplayName) { Write-Output 'No error' }
The specified wildcard character pattern is not valid: Test Application [Fail-Me]
At line:1 char:5
+ if ($null -notlike $DisplayName) { Write-Output 'No error' }
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], WildcardPatternException
    + FullyQualifiedErrorId : RuntimeException
```

**Comment by homotechsual** [comment]
Could use:

```powershell
-not ([string]::IsNullOrWhiteSpace($DisplayName))
```

Instead

**Comment by homotechsual** [comment]
or, as Luke pointed out to me on Discord - `-ne` instead of `-notlike` :-D

**Comment by homotechsual** [comment]
https://github.com/lwhitelock/NinjaOneAutomation/blob/bc067e0fe5225f84a88bb9a4529b19d1af53ba5b/DocumentationScripts/Check-App-Vulnerabilities.ps1#L35 still has a `-notlike`

**Comment by lwhitelock** [comment]
Fixed
